### ISSUE TITLE
IP address is illegal

### ISSUE THREAD

**Issue by skyler4722** [ucectoplasm/eft-packet#17]
Whenever I run the .exe it says IP address is illegal. Does anyone know how to fix this? Help is greatly appreciated.

**Comment by JIPdoixc** [comment]
This is a good time to stop. Judging by your clearly depicted inaptitude, you will only get yourself banned.

**Comment by Not-a-true-statement** [comment]
I am in agreement!

**Comment by Pythontechie21** [comment]
Hmm... did you change the ip address listings in the main.cpp file? in the quotes for  Local_adapter_ip_address put the ip of the computer you have running the hack and for MACHINE_PLAYING_GAME_IP_ADDRESS put the computers ip of the one running tarkov and then rebuild. sorry if you already did this, I figured it's the easiest solution. Also to the two people above me, people can learn if people take time to help them when they ask. and nothing from his statement said he was in any way incompetent to do It, he literally just asked for help, that's not an inaptitude.

**Comment by skyler4722** [comment]
> Hmm... did you change the IP address listings in the main.CPP file? in the quotes for LOCAL_ADAPTER_IP_ADDRESS put the IP of the computer you have running the hack and for MACHINE_PLAYING_GAME_IP_ADDRESS put the computers IP of the one running tarkov, you can get these from ipconfig on windows. and then rebuild. sorry if you already did this, I figured it's the easiest solution. Also to the two people above me, people can learn if people take time to help them when they ask. and nothing from his statement said he was in any way incompetent to do It, he literally just asked for help, that's not an inaptitude.

Thanks man, I appreciate the help!

**Comment by JIPdoixc** [comment]
Should I have stated that "hint: "fill.me.in" is not a legal IP address"?
How's it not inaptitude if one can tell that skyler hasn't taken a serious look at the source code before trying to run it? It follows that the setup may be incorrect, too, thus potentially leading to a ban.

While I may come off as spiteful, this projects purpose simply isn't to spoonfeed inept individuals so that they may run free `hax`.

**Comment by Pythontechie21** [comment]
> Should I have stated that "hint: "fill.me.in" is not a legal IP address"?
> How's it not inaptitude if one can tell that skyler hasn't taken a serious look at the source code before trying to run it? It follows that the setup may be incorrect, too, thus potentially leading to a ban.
> 
> While I may come off as spiteful, this projects purpose simply isn't to spoonfeed inept individuals so that they may run free `hax`.

You don't know how much he knows on the subject, regardless, it's a hack, I'm sure people understand hacks can get you banned and are willing to take that risk. You are telling me you have never had an oversight or code tunnel vision where you have a simple problem but merely overlooked it in the thousands of lines of code? Even if he knows absolutely nothing about this, telling him that is basically like telling him he has a stupid question and just shouldn't try to learn about it. A lot of people may want to look into this as a learning tool as well, to understand how one intercepts the packets and modifies the values, what better way to do that than run existing code and modify it piece by piece to understand how it works. helping someone with an issue is not spoonfeeding, he didn't come here saying "how do I build it, how do I fix this, how do I fix that, can you do it for me" He simply asked a question that only needs a few sentence answer. Not to mention, it comes off as kind of cocky to assume how knowledgeable he is on the topic. Besides these issues on github are there for people to ask questions and get help, not someone telling them they're stupid and should just give up lol.
