### ISSUE TITLE
I hate to be that guy... But, i don't how to fix this, i've spent a couple of hours searching around, but to no avail...

### ISSUE THREAD

**Issue by Siraff** [ucectoplasm/eft-packet#2]
VCBUILD : fatal error C1047: The object or library file '.\x64\Release\common.obj' was created with an older compiler than other objects; rebuild old objects and libraries
  LINK : fatal error LNK1257: code generation failed

I'm using Visual Studio 2017 Community edition. So far i've tried to switch off /GL and /LTCG

**Comment by mq1n** [comment]
you should use Visual Studio 2019

**Comment by Siraff** [comment]
Upgraded to visual studio 2019 community, and tried to build. The same error is not appearing, but a new one is: 

1>main.obj : error LNK2001: unresolved external symbol __imp_ntohs
1>Common++.lib(IpAddress.obj) : error LNK2001: unresolved external symbol inet_ntop
1>Common++.lib(IpAddress.obj) : error LNK2001: unresolved external symbol __imp_inet_pton
1>Packet++.lib(EthLayer.obj) : error LNK2001: unresolved external symbol __imp_htons
1>Packet++.lib(IPv4Layer.obj) : error LNK2001: unresolved external symbol __imp_htonl
1>Packet++.lib(GreLayer.obj) : error LNK2001: unresolved external symbol __imp_ntohl
1>Pcap++.lib(PcapLiveDeviceList.obj) : error LNK2001: unresolved external symbol __imp_GetNetworkParams
1>Pcap++.lib(PcapLiveDevice.obj) : error LNK2001: unresolved external symbol __imp_GetAdaptersInfo

**Comment by Siraff** [comment]
Fixed 6 of the issues by adding the library Ws2_32.lib. Still getting these errors though: 

>Pcap++.lib(PcapLiveDeviceList.obj) : error LNK2001: unresolved external symbol __imp_GetNetworkParams
1>Pcap++.lib(PcapLiveDevice.obj) : error LNK2001: unresolved external symbol __imp_GetAdaptersInfo

**Comment by mq1n** [comment]
you should link iphlpapi.lib too

**Comment by Siraff** [comment]
Hey, that actually worked. Can you please post these solutions in unkowncheats, so folks who have the same issues can fix it. I'll get back and see if the program works. Thanks for your help man!
