### ISSUE TITLE
Detection Vector

### ISSUE THREAD

**Issue by njbrown09** [ucectoplasm/eft-packet#3]
Im going to stop using this until this is addressed, but isnt the VPN a detection risk? I was watching a defcon video on detecting MITM attacks, and one of the common methods the guy said they use to detect them was with tracert, and if the first route is abnormally low (1-3ms) and from a local ip, they were likely getting MITM'd. BE isnt dumb, couldnt they detect this radar with that method?

**Comment by ucectoplasm** [comment]
I'm sure there are many ways BE could detect and eliminate playing through a VPN but I doubt they would ban you for it. Connecting through a VPN is a pretty normal thing to do; at worst they would just prevent playing through a VPN.

**Comment by Esya** [comment]
Will add that otherwise you could just run the packet analyzer on a distant machine, and that you can also just do port mirroring if you have a managed switch, which is absolutely untracable
