### ISSUE TITLE
Scavs missing from Observers

### ISSUE THREAD

**Issue by protoplas** [ucectoplasm/eft-packet#7]
I added prints inside `create_obs` to print the name of each observer when it's created for the first time. I can see all player observers being printed correctly, but for some reason only 1-2 scavs get created as observers in the game map, either with names or as Unknown. Do you know why other scavs are missing? The "Unknown" makes sense to me based on your code comment, but I can't figure out why the majority of scavs aren't getting registered at all.

**Comment by ucectoplasm** [comment]
I haven't encountered this before. It could be caused by packet loss, or maybe packets arriving out-of-order? We don't current handle packet order, so in theory it is possible that, if you receive an update before a spawn message, there may be some Unknowns.
