### ISSUE TITLE
Network code refactoring pull-request

### ISSUE THREAD

**Issue by protoplas** [ucectoplasm/eft-packet#8]
I'd like to build a conventional top-down radar on top of your packet interceptor instead of the 3D radar you have at the moment. However, `main.cpp` currently has GUI code mixed with networking code. Would you be open to a pull request with all networking code from main.cpp moved into its own class?

**Comment by ucectoplasm** [comment]
Definitely, but keep in mind the current architecture.

`main.cpp` is where the network code that handles UNET packet headers (and save/load/intercept networking traffic) exists.
`tk_net.cpp` is where the networking code from EFT exists.

I would therefore propose the most obvious refactor would be: move the UNET network code from `main.cpp` to `unet.cpp`. (if you did this you could also move all of the unet stuff from the header to the source file).

A further improvement could be: move the rendering code from `main.cpp` to `render.cpp` (or some other appropriately named file).
